{
 "title": "HAB Flight Data",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "GPS Position",
   "type": "geomap",
   "gridPos": { "h": 23, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "measurement": "payloaddata",
     "query": "SELECT latitude, longitude, altitude FROM payloaddata WHERE $timeFilter",
     "select": [
      [
       { "params": [ "latitude" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Photo",
   "type": "text",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "options": {
    "content": "<div id=\"myTextPanel\" class=\"ng-scope\">\n    <script type=\"text/javascript\">\n      function updateImage() {\n        var url = window.location.protocol + \"//\" + window.location.hostname + \"/latest.jpg#\" + new Date().getTime();\n        $(\"#imgtagid\").attr(\"src\", url);\n        $(\"#hregtagid\").href = url;\n      }\n      angular.element('grafana-app').injector().get('timeSrv').dashboard.events.emitter.addListener('refresh', updateImage)\n    </script>\n    <a href=\"\" id=\"hregtagid\">\n      <img id=\"imgtagid\" src=\"http://192.168.0.110/latest.jpg\" /> \n    </a>\n</div>"
   },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "payloaddata",
     "select": [
      [
       { "params": [ "fixstatus" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Last Update",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "payloaddata",
     "query": "SELECT rpicputemperature FROM payloaddata",
     "select": [
      [
       { "params": [ "altitude" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "GPS Fix Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "payloaddata",
     "query": "SELECT fixstatus FROM payloaddata WHERE $timeFilter",
     "select": [
      [
       { "params": [ "fixstatus" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "GPS Satellites",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 20, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "payloaddata",
     "query": "SELECT satellites FROM payloaddata WHERE $timeFilter",
     "select": [
      [
       { "params": [ "satellites" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU Temperature",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "payloaddata",
     "query": "SELECT rpicputemperature FROM payloaddata WHERE $timeFilter",
     "select": [
      [
       { "params": [ "rpicputemperature" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Altitude",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "payloaddata",
     "query": "SELECT altitude FROM payloaddata WHERE $timeFilter",
     "select": [
      [
       { "params": [ "altitude" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "payloaddata",
     "query": "SELECT temperature FROM payloaddata WHERE $timeFilter",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Altitude",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "targets": [
    {
     "alias": "GPS Altitude",
     "measurement": "payloaddata",
     "query": "SELECT altitude FROM payloaddata WHERE $timeFilter",
     "select": [
      [
       { "params": [ "altitude" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Pressure Altitude",
     "query": "SELECT 44330.0 * (1.0 - pow(pressure / 1013.25, 0.1903)) FROM payloaddata WHERE $timeFilter\n"
    }
   ]
  },
  {
   "title": "Pressure",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "payloaddata",
     "query": "SELECT pressure FROM payloaddata WHERE $timeFilter",
     "select": [
      [
       { "params": [ "pressure" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "payloaddata",
     "query": "SELECT humidity FROM payloaddata WHERE $timeFilter",
     "select": [
      [
       { "params": [ "humidity" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "measurement": "payloaddata",
     "query": "SELECT temperature FROM payloaddata WHERE $timeFilter",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Pressure",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "targets": [
    {
     "measurement": "payloaddata",
     "query": "SELECT pressure FROM payloaddata WHERE $timeFilter",
     "select": [
      [
       { "params": [ "pressure" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}